### ISSUE TITLE
Get xml throw exception

### ISSUE THREAD

**Issue by yooo1999** [Ucnt/aws-s3-downloader#10]
`python download_bucket.py -n pdfdays -x` throw exception

```
http://pdfdays.s3.amazonaws.com/?list-type=2&start-after=clips/20100806/N10AA10/Clipping_01__dbb3a5ebc0.jpg
Traceback (most recent call last):
  File "download_bucket.py", line 40, in <module>
    download_bucket_public(bucket=bucket)
  File "c:\tmp\aws-s3-downloader\module\download_bucket_public.py", line 52, in download_bucket_public
    keys.extend(add_page(bucket, request))
TypeError: 'NoneType' object is not iterable
```

**Comment by Ucnt** [comment]
Fixed.
